### PR TITLE
cargo: avoid deprecated syntax in license field

### PR DESCRIPTION
**Pull request by bgilbert**
https://doc.rust-lang.org/cargo/reference/manifest.html#slash

### CODE REVIEW

**Review by prestist — APPROVED** [review]
Thanks for doing this
LGTM

**Review by cgwalters — APPROVED** [review]
Looks sane to me, though note this repository is deprecated and we could potentially just stop syncing CI for it.

**Comment by bgilbert** [comment]
Yeah, my thinking is that it's easier to sync CI here than to let this repo diverge and possibly deal with surprises down the road.

**Comment by cgwalters** [comment]
Yeah makes sense.  Actually bootupd still uses this, so we'll want to maintain this until that's ported.

**Pull request merged**
